spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=UTF-8
    username: javaConnection
    password: tztlx13GBT
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: 123
      web-stat-filter: # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*</param-value>'
      aop-patterns: com.atguigu.springboot.* # 监控 Spring Bean
      filters: stat,wall
      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

  jdbc:
    template:
      query-timeout: 3

#  redis: # 两种连接方式 url 或 host + port + password
#    url: redis://user:password@example.com:6379
#    host: example.com
#    port: 6379
#    password: user:password
##    client-type: jedis # 设置Jedis为客户端

#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml #全局配置文件位置 注意和configuration冲突
#  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
#  type-aliases-package: com.atguigu.springboot.bean
#  configuration: # 指定mybatis全局配置文件中的相关配置项
#    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml

